name: 'Setup Build Environment'
description: 'Sets up Java, Rust, Homebrew dependencies, and tools required for builds.'

inputs:
  java-version:
    description: 'Java version'
    required: false
    default: '17'
  os-type:
    description: 'OS type (macos or linux)'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Install Java"
      uses: actions/setup-java@v4
      continue-on-error: true
      with:
        java-version: ${{ inputs.java-version }}
        distribution: zulu

    - name: "Setup Homebrew (macOS)"
      if: inputs.os-type == 'macos'
      shell: bash
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: "Install rust toolchain (Linux)"
      if: inputs.os-type == 'linux'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y rustc build-essential curl

    - name: "Install Dependencies (macOS)"
      if: inputs.os-type == 'macos'
      shell: bash
      run: |
        brew install autoconf automake libtool rustup
        brew tap messense/macos-cross-toolchains
        brew install --overwrite x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

    - name: "Clean Python Symlinks (macOS)"
      if: inputs.os-type == 'macos'
      shell: bash
      run: |
        rm -f '/usr/local/bin/2to3' '/usr/local/bin/python3' '/usr/local/bin/python3-config'

    - name: "Install Rust Targets"
      shell: bash
      run: |
        rustup target add armv7-linux-androideabi \
          i686-linux-android \
          aarch64-linux-android \
          x86_64-linux-android \
          aarch64-apple-darwin \
          x86_64-apple-darwin \
          aarch64-unknown-linux-gnu \
          x86_64-unknown-linux-gnu

    - name: "Setup Xcode (macOS)"
      if: inputs.os-type == 'macos'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: "Install wasm-pack"
      shell: bash
      run: cargo install wasm-pack