name: Debug

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  unified_release:
    name: Debug
    runs-on: macos-latest

    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: zulu

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Test variables
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.HYP_BOT_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_version: ${{ github.event.inputs.version }}
        run: |
          ./gradlew debugSigningProperties
