name: Sign File with GPG

# Allow manual runs from the Actions tab
on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a file to sign
        run: echo "This is the content of our file." > artifact.txt

      - name: Sign the file ✍️
        env:
          ARMORED_KEY: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          GPG_PASSWORD: ${{ secrets.HYP_BOT_GPG_PASSWORD }}
        run: |
          # Import the GPG key using --batch to ensure it's non-interactive
          echo "$ARMORED_KEY" | gpg --batch --import
          if [ $? -ne 0 ]; then
              echo "GPG key import failed."
              exit 1
          fi

          # Sign the file non-interactively
          echo "$GPG_PASSWORD" | gpg --batch --pinentry-mode loopback --passphrase-fd 0 --armor --detach-sign artifact.txt
          if [ $? -ne 0 ]; then
              echo "GPG signing failed."
              exit 1
          fi

          echo "File signed successfully!"

      - name: Show resulting files
        run: |
          echo "Generated files:"
          ls -l